config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'
  get '/blog', to: 'static_pages#blog'
  get '/shop', to: 'static_pages#shop'
  get '/cart', to: 'static_pages#cart'
  
  resources :users
  resources :microposts,          only: [:create, :destroy]
  
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/micropost.rb
class Micropost < ApplicationRecord
    belongs_to :user
    default_scope -> { order(created_at: :desc) }
    validates :user_id, presence: true
    validates :content, presence: true, length: { maximum: 140 }
end

app/models/user.rb
class User < ApplicationRecord
    attr_accessor :remember_token
    before_save { self.email = email.downcase }
    has_many :microposts, dependent: :destroy
    
    validates :name,  presence: true, length: { maximum: 50 }
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
    has_secure_password
    validates :password, presence: true, length: { minimum: 6 }
    
    def self.digest(string)
        cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                      BCrypt::Engine.cost
        BCrypt::Password.create(string, cost: cost)
    end
    def self.new_token
        SecureRandom.urlsafe_base64
    end
    def remember
        self.remember_token = User.new_token
        update_attribute(:remember_digest, User.digest(remember_token))
    end
    def authenticated?(remember_token)
        return false if remember_digest.nil?
        BCrypt::Password.new(remember_digest).is_password?(remember_token)
    end
    def forget
        update_attribute(:remember_digest, nil)
    end
    def feed
        Micropost.where("user_id = ?", id)
    end
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
  
   private
    def logged_in_user
      unless logged_in?
        store_location
        flash[:danger] = "Please log in."
        redirect_to login_url
      end
    end
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
  before_action :logged_in_user, only: [:create, :destroy]
  before_action :correct_user,   only: :destroy
  
  def create
      @micropost = current_user.microposts.build(micropost_params)
    if @micropost.save
      flash[:success] = "Micropost created!"
      redirect_to root_url
    else
      @feed_items = []
      render 'static_pages/home'
    end
  end

  def destroy
    @micropost.destroy
    flash[:success] = "Micropost deleted"
    redirect_to request.referrer || root_url
  end
  private

    def micropost_params
      params.require(:micropost).permit(:content)
    end
     def correct_user
      @micropost = current_user.microposts.find_by(id: params[:id])
      redirect_to root_url if @micropost.nil?
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      params[:session][:remember_me] == '1' ? remember(user) : forget(user)
      redirect_to user
    else
      flash.now[:danger] = 'Invalid email/password combination' 
      render 'new'
    end
  end

  def destroy
    log_out if logged_in?
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
   
  end

  def blog
     if logged_in?
      @micropost  = current_user.microposts.build
      @feed_items = current_user.feed.paginate(page: params[:page])
    end
  end

  def shop
  end

  def cart
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def show
    @user= User.find(params[:id])
    @microposts = @user.microposts.paginate(page: params[:page])
  end
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params) 
    if @user.save
      flash[:success] = "Welcome to the SewPurpleCreations!"
      redirect_to @user
    else
      render 'new'
    end
  end
  
  before_action :logged_in_user, only: [:index, :edit, :update, :destroy]

  def show
    @user = User.find(params[:id])
     @microposts = @user.microposts.paginate(page: params[:page])
  end
  private

    def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation)
    end
     private

    def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation)
    end

    
    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end

    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/microposts_helper.rb
module MicropostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    
  def log_in(user)
    session[:user_id] = user.id
  end
  
  def remember(user)
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end
  
  def current_user?(user)
    user == current_user
  end
  
  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    elsif (user_id = cookies.signed[:user_id])
      user = User.find_by(id: user_id)
      if user && user.authenticated?(cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end
    
  def logged_in?
    !current_user.nil?
  end
  
  def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end
  
  def log_out
    forget(current_user)
    session.delete(:user_id)
    @current_user = nil
  end
    
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
    def gravatar_for(user, size: 80)
        gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
        gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
        image_tag(gravatar_url, alt: user.name, class: "gravatar")
    end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title> <%= yield(:title) %> | SewPurpleCreations </title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="header">
  
        <ul>
            <li><%= link_to "Home", root_path %></li>
            <li><%= link_to "Blog", blog_path %></li>
            <li><%= link_to "Shop", shop_path %></li>
            <li><%= link_to "Cart", cart_path %></li>
            <% if logged_in? %>
              <li><%= link_to "Profile", user_path(current_user) %></li>
              
            <% else %>
              <li><%= link_to "Log in", login_path %></li>
            <% end %>
             
        </ul>
      </div>
          <h1>Sew Purple Creations</h1>
          <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
 
<%= yield %>
<%= link_to image_tag("SewPurple Watermark.png", alt:"image of the shop logo"), root_path, class:"small" %>
</body>
</html>

app/views/microposts/_micropost.html.erb
<li id="<%= micropost.id %>">
  <%= link_to gravatar_for(micropost.user, size: 50), micropost.user %>
  <span class="user"><%= link_to micropost.user.name, micropost.user %></span>
  <span class="content"><%= micropost.content %></span>
  <span class="timestamp">
    Posted <%= time_ago_in_words(micropost.created_at) %> ago.
    <% if current_user?(micropost.user) %>
      <%= link_to "delete", micropost, method: :delete,
                                       data: { confirm: "You sure?" } %>
    <% end %>
  </span>
</li>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <ol class="microposts">
    <%= render @feed_items %>
  </ol>
  <%= will_paginate @feed_items %>
<% end %>

app/views/shared/_micropost_form.html.erb
<%= form_for(@micropost) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
    <%= f.text_area :content, placeholder: "Compose new micropost..." %>
  </div>
  <%= f.submit "Post", class: "btn btn-primary" %>
<% end %>

app/views/shared/_user_info.html.erb
<%= link_to gravatar_for(current_user, size: 50), current_user %>
<h1><%= current_user.name %></h1>
<span><%= link_to "view my profile", current_user %></span>
<span><%= pluralize(current_user.microposts.count, "micropost") %></span>

app/views/static_pages/blog.html.erb
<% provide(:title, "post")%>
<% if logged_in? %> 
  <div class="row">
    <aside class="col-md-4">
      <section class="user_info">
        <%= render 'shared/user_info' %>
      </section>
      <section class="micropost_form">
        <%= render 'shared/micropost_form' %>
      </section>
    </aside>
  </div>
  <div class="col-md-8">
      <p class= "profile"><b>Feed</b></p>
      <%= render 'shared/feed' %>
    </div>
<% else %>
<% end %>

app/views/static_pages/cart.html.erb
<% provide(:title, "Cart")%>

<P class="profile"><b>Shopping Cart</b></P>
 
 <p>
     <%= link_to image_tag("dragon.jpg"), shop_path, class:"itemImage" %>
     <span class= "desc">Dragon Plushie</span><br>
     <span class="desc_2">Blue/Green</span>
     <%= link_to image_tag("x.png"), cart_path, class: "x" %>
     
    <br>
    <span class="price">$25</span>
    <br>
    
    <%= link_to image_tag("divider.png"), shop_path, class: "divider" %>    
    <br>
    <span class="price"><b>Total:  </b> $25</span>
    <br><br>
   
 </p>
     

app/views/static_pages/home.html.erb
<% provide(:title, "Home")%>
       <p>Hello and welcome to my website where I sell crafts that I make.
       <br><br>
      
<span class="slideshow-container">
    <span class="mySlides">
        <%= link_to image_tag("dragon.jpg", alt:"image of dragon"), root_path, class:"showimg" %>
        <span class="text">Handmade Dragon Plush</span>
    </span>    
    
    <span class="mySlides">
        <%= link_to image_tag("wing-s-g.jpg", alt:"gold wings"), root_path, class:"showimg" %>
        <span class="text">Gold shoe wings</span>
    </span>
        
    <span class="mySlides">
        <%= link_to image_tag("onshoe.jpg", alt:"on shoe wings"), root_path, class:"showimg" %>
        <span class="text">Opalesent Shoe wings</span>
    </span>
</span>
<br>

  <span class="dot" onclick="currentSlide(1)"></span> 
  <span class="dot" onclick="currentSlide(2)"></span> 
  <span class="dot" onclick="currentSlide(3)"></span> 
       
  <a class="prev" onclick="plusSlides(-1)">&#10094;</a>
  <a class="next" onclick="plusSlides(1)">&#10095;</a>
  </p>

app/views/static_pages/shop.html.erb
<% provide(:title, "Shop")%>
<p>
    <%= link_to image_tag("dragon.jpg"), shop_path, class:"shopImage" %><br>
     <span class= "desc">Dragon Plushie</span><br>
     <span class="desc_2">Blue/Green</span>
     <%= link_to image_tag("cart.png"), cart_path, class: "x" %>
     
     
    <br>
    <span class="price">$25</span>
    <br><br><br><br><br><br><br>
    <%= link_to image_tag("divider.png"), shop_path, class: "divider" %><br><br><br><br><br><br>
    
    <%= link_to image_tag("wing-s-g.jpg"), shop_path, class:"shopImage" %><br>
     <span class= "desc">Shoe wings</span><br>
     <span class="desc_2">Silver OR Gold OR opalescence</span>
     <%= link_to image_tag("cart.png"), cart_path, class: "x" %>
     
     
    <br>
    <span class="price">$15</span>
    <br><br><br><br>
    <%= link_to image_tag("divider.png"), shop_path, class: "divider" %>    
</p>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<p class="up"><b>Sign up</b></p>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user, url: signup_path) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirm Password" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>
</div class="already>"><p><i>Already have and account?</i><%= link_to "Log in", login_path %></p>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<p class="profile">
  <b>User Profile</b>
</p>

<p class="info">
    <span class="out">
    <%= link_to "Log out", logout_path, method: :delete %>
    </span>
  <%= gravatar_for @user %>
  <br>
   <b>User name: </b><%= @user.name %>
   <br>
   <b>User email: </b><%= @user.email %>
   <br><br><br>
</p>

 
<div class="col-md-8">
    <% if @user.microposts.any? %>
      <p class="profile">
  <b>Feed</b>(<%= @user.microposts.count %>)
</p>  
      <ol class="microposts">
        <%= render @microposts %>
      </ol>
      <%= will_paginate @microposts %>
    <% end %>